[project]
name = "streamlit-api"
version = "0.1.0"
description = "Test project for streamlit-api"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.40.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
