name: "Test Reporting for CI builds"
on:
  workflow_run:
    workflows: [".NET CI"]
    types:
      - completed

jobs:
  test-reporting:
    permissions:
      contents: read
      actions: read
      checks: write
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Generate Test Report
        uses: phoenix-actions/test-reporting@v15
        id: test-report
        with:
          name: ".NET Test report $1"
          path: "*.trx"
          reporter: dotnet-trx
          artifact: /test-results-(.*)/
